Update routes.js (#181)
token ?? is recently added and hence may not be available on armv6l platforms.
Fixes:
/opt/node/lib/node_modules/crontab-ui/routes.js:2
var base_url = process.env.BASE_URL ?? '';
                                     ^
SyntaxError: Unexpected token ?